### ISSUE TITLE
Error on integration setup

### ISSUE THREAD

**Issue by sammyke007** [adechant/ha_vscode#3]
Hi

I tried to setup this integration, but after tunnel creation, I can't continue. I'm stuck on this error:

![Screenshot_2024-01-20-00-25-47-21_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/adechant/ha_vscode/assets/33524412/bc4cf506-adb3-44d9-b272-9d750a571fcf)

What am I doing wrong?

**Comment by sammyke007** [comment]
Ok, enabling the switch made it work, but is it normal behavior that the timeout can't be changed?

**Comment by tbrasser** [comment]
Seems you need to pass a float instead of an int. It worked when I put in 0.7.

Another gotcha, the switch doesn't show up under the integration. Just search globally for it.
